services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - ENC_DOMAIN=enc.meanii.dev
      - AUTH_API=auth_server:8000
    container_name: rtmp_server
    volumes:
      - ./data:/opt/data
      - ./certs:/opt/certs
      - ./nginx.conf:/etc/nginx/nginx.conf.template

  auth:
    build: ./auth
    container_name: auth_server